### ISSUE TITLE
ycmd server 无法启动

### ISSUE THREAD

**Issue by liangcha-ck** [snakeleon/YouCompleteMe-x86#2]
之前用老版本好好的，用last commit版本ycmd 无法启动了，自己找不到解决办法，大概是什么原因？

**操作系统： windwos 7 64位**
**GVIM版本：8.0 （官网下载版本）**
**python版本：2.7.10**
**message消息显示：**

```
The ycmd server SHUT DOWN (restart with ':YcmRestartServer'). Unexpected error while loading the YCM core library. Run ':YcmToggleLogs stderr' to check the logs.
```

**YCM错误日志：**

```
2016-10-09 14:32:54,894 - ERROR - DLL load failed: 找不到指定的模块。
Traceback (most recent call last):
  File "d:\PROGRA~1\Vim\vimfiles\bundle\YOUCOM~1\THIRD_~1\ycmd\ycmd\server_utils.py", line 95, in CompatibleWithCurrentCore
    ycm_core = ImportCore()
  File "d:\PROGRA~1\Vim\vimfiles\bundle\YOUCOM~1\THIRD_~1\ycmd\ycmd\server_utils.py", line 87, in ImportCore
    import ycm_core as ycm_core
ImportError: DLL load failed: 找不到指定的模块。
```

**Comment by snakeleon** [comment]
错误显示是python 动态库找不到，现在静态编译的版本已经切换到 Python 支持: 3.5.2 
所以请安装最新版的 Python 3，就可正常工作。
PS：注意相对应的版本，VIM 如果是64位的请安装64位python 3 , 相应的YCM也安装64位的，32位的同理。
官网版本似乎编译的不支持导入最新版的python 3.5.2 dll 文件，请到 Vim builds for Windows [https://tuxproject.de/projects/vim/] 下载第三方编译的版本覆盖到你的安装目录。

**Comment by liangcha-ck** [comment]
@snakeleon 多谢。安装了python 3.5.2，设置`ycm_server_python_interpreter` 可以正常运行了。
